// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHTznwLb01BUaazzSduSZxal4gpmVzjH4',
    appId: '1:953761043201:web:db2a3061180f090c468100',
    messagingSenderId: '953761043201',
    projectId: 'estatepay-77ada',
    authDomain: 'estatepay-77ada.firebaseapp.com',
    storageBucket: 'estatepay-77ada.appspot.com',
    measurementId: 'G-LVHW7LECM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6ck_4avL7AI-ap1XwjSX1nvdOdXYOJ0o',
    appId: '1:953761043201:android:ebed887f31fb0735468100',
    messagingSenderId: '953761043201',
    projectId: 'estatepay-77ada',
    storageBucket: 'estatepay-77ada.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO0PFp7aBEDn3nFatts3JrSh56QB2B7nY',
    appId: '1:953761043201:ios:28234b42f9ed84a4468100',
    messagingSenderId: '953761043201',
    projectId: 'estatepay-77ada',
    storageBucket: 'estatepay-77ada.appspot.com',
    iosClientId: '953761043201-8rvdc40l0imug6dadue2sr8qord6vuts.apps.googleusercontent.com',
    iosBundleId: 'com.example.estatepay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO0PFp7aBEDn3nFatts3JrSh56QB2B7nY',
    appId: '1:953761043201:ios:28234b42f9ed84a4468100',
    messagingSenderId: '953761043201',
    projectId: 'estatepay-77ada',
    storageBucket: 'estatepay-77ada.appspot.com',
    iosClientId: '953761043201-8rvdc40l0imug6dadue2sr8qord6vuts.apps.googleusercontent.com',
    iosBundleId: 'com.example.estatepay',
  );
}
